[tool.portray]
extra_dirs = ["resources"]

[tool.portray.mkdocs]
repo_url = "https://github.com/fidelity/stoke"
extra_javascript = [
    "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js",
    "resources/js/config.js"
]
extra_css = [
    "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/atom-one-light.min.css",
    "resources/css/extra_colors.css"
]

[[tool.portray.mkdocs.markdown_extensions]]
[tool.portray.mkdocs.markdown_extensions."pymdownx.highlight"]
use_pygments = false

[tool.portray.mkdocs.theme]
favicon = "resources/images/stoke_small.png"
logo = "resources/images/stoke_small.png"
name = "material"
features = ["navigation.tabs", "navigation.top"]

[tool.portray.mkdocs.theme.palette]
scheme = "slate"
primary = "white"
accent = "indigo"

[tool.portray.mkdocs.theme.icon]
repo = "fontawesome/brands/github-alt"

[[tool.portray.mkdocs.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/ncilfone"

[[tool.portray.mkdocs.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/ncilfone/"

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
Installation = "docs/Installation.md"

[[tool.portray.mkdocs.nav]]
Contributing = "CONTRIBUTING.md"


[tool.isort]
profile = "black"