# This workflow will run isort and black linters on PRs

name: lint

# on: workflow_dispatch
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('REQUIREMENTS.txt') }}-${{ hashFiles('./requirements/DEV.txt') }}

    - name: Install dependencies and dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r ./requirements/DEV.txt

    - name: Run isort linter
      run: |
        isort --check . --skip="debug" --skip="versioneer.py" --skip="tests" --skip="_version.py"

    - name: Run black linter
      run: |
        black --check . --exclude="versioneer.py|_version.py|debug|tests"
